"""create runs and targets

Revision ID: 60937e55c284
Revises:
Create Date: 2026-09-18 21:03:53.359215

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "60937e55c284"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "buybox_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vertical", sa.String(length=100), nullable=False),
        sa.Column("market", sa.String(length=120), nullable=False),
        sa.Column("headcount_min", sa.Integer(), nullable=False),
        sa.Column("headcount_max", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_buybox_runs")),
    )
    op.create_index(
        op.f("ix_buybox_runs_market"), "buybox_runs", ["market"], unique=False
    )
    op.create_index(
        op.f("ix_buybox_runs_vertical"), "buybox_runs", ["vertical"], unique=False
    )
    op.create_table(
        "target_companies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("dedupe_hash", sa.String(length=200), nullable=False),
        sa.Column("legal_name", sa.String(length=260), nullable=False),
        sa.Column("street_line", sa.String(length=400), nullable=True),
        sa.Column("locality", sa.String(length=100), nullable=True),
        sa.Column("region", sa.String(length=40), nullable=True),
        sa.Column("main_phone", sa.String(length=50), nullable=True),
        sa.Column("web_url", sa.String(length=500), nullable=True),
        sa.Column("fit_score", sa.Float(), nullable=False),
        sa.Column("tier", sa.String(length=20), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["buybox_runs.id"],
            name=op.f("fk_target_companies_run_id_buybox_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_target_companies")),
        sa.UniqueConstraint("run_id", "dedupe_hash", name="uq_run_dedupe"),
    )
    op.create_index(
        op.f("ix_target_companies_run_id"), "target_companies", ["run_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_target_companies_run_id"), table_name="target_companies")
    op.drop_table("target_companies")
    op.drop_index(op.f("ix_buybox_runs_vertical"), table_name="buybox_runs")
    op.drop_index(op.f("ix_buybox_runs_market"), table_name="buybox_runs")
    op.drop_table("buybox_runs")
    # ### end Alembic commands ###
