"""add source status and email

Revision ID: b93f7c8b3942
Revises: 60937e55c284
Create Date: 2026-09-18 22:14:11.217456

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b93f7c8b3942"
down_revision: str | Sequence[str] | None = "60937e55c284"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "buybox_runs",
        sa.Column(
            "source_status", sa.String(length=20), server_default="live", nullable=False
        ),
    )
    op.add_column(
        "target_companies", sa.Column("email", sa.String(length=254), nullable=True)
    )
    # ### end Alembic commands ###
    # Older runs tagged placeholder rows as "seed". Rename to the new "sample".
    op.execute(
        """
        UPDATE target_companies
        SET meta = jsonb_set(meta, '{origin}', '"sample"')
        WHERE meta->>'origin' = 'seed'
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(
        """
        UPDATE target_companies
        SET meta = jsonb_set(meta, '{origin}', '"seed"')
        WHERE meta->>'origin' = 'sample'
        """
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("target_companies", "email")
    op.drop_column("buybox_runs", "source_status")
    # ### end Alembic commands ###
