"""add source detail

Revision ID: ba251449d823
Revises: b93f7c8b3942
Create Date: 2026-09-18 23:56:29.247335

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ba251449d823"
down_revision: str | Sequence[str] | None = "b93f7c8b3942"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "buybox_runs", sa.Column("source_detail", sa.String(length=300), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("buybox_runs", "source_detail")
    # ### end Alembic commands ###
